firstnames:
  - Rigó
  - Erős
  - Vajonőr
  - Cikáyn
  - Tompoló
  - Mikorka
  - Galambos
  - Techno
  - Dundi
  - Kokkeró
lastnames:
  - Kálmán
  - Jancsi
  - Galamphos
  - Pepe
  - Gregory
  - Wise Mystical Tree
  - Lacatusu